### PR TITLE
Closes #47: replace system_model submodule w/ directory

### LINKED ISSUE #47: move system_model folder from project-tetra to project-tetra-docs repo
`system_model` folder currently subsides as a submodule from the project-tetra repo and s/b moved back to the project-tetra-docs repo.

### PR DESCRIPTION
**Pull request by capsulecorplab**
- update symbolic links to point to system_model folder in project-tetra-docs root directory

### CODE REVIEW

**Comment by professor-nimrod** [comment]
Two concerns from me:
-For some reason, the UML diagrams aren't rendering when I run the Hugo site on localhost (just getting plaintext). However, they render fine when I render the corresponding .adoc files using a VSCode extension, so I'm assuming it's just a dependency issue on my end
-`system_model/ibd-ventilator-splitter-assembly.puml` & `system_model/ibd-electronic-sensing-system.puml` can be deleted, as they're duplicates of `system_model/ibd-system-ventilator-splitter-assembly-airflow.puml` & `system_model/ibd-system-electronic-sensing-system-dataflow.puml`, respectively

Otherwise, LGTM

**Comment by capsulecorplab** [comment]
@chrismolinari456 Thanks for the notes! 
>-For some reason, the UML diagrams aren't rendering when I run the Hugo site on localhost (just getting plaintext). However, they render fine when I render the corresponding .adoc files using a VSCode extension, so I'm assuming it's just a dependency issue on my end

Are you running the `serve.sh` script or `hugo serve` command?

>-system_model/ibd-ventilator-splitter-assembly.puml & system_model/ibd-electronic-sensing-system.puml can be deleted, as they're duplicates of system_model/ibd-system-ventilator-splitter-assembly-airflow.puml & system_model/ibd-system-electronic-sensing-system-dataflow.puml, respectively

Good catch, they should've been deleted.

**Comment by professor-nimrod** [comment]
@capsulecorplab You're right; I was using `hugo serve`. Everything LGTM!

**Review by professor-nimrod — APPROVED** [review]

**Comment by capsulecorplab** [comment]
Temporarily converting PR to draft until we resolve #52

**Comment by capsulecorplab** [comment]
removed unused duplicate .puml files

**Comment by capsulecorplab** [comment]
@chrismolinari456 rebased off `dev` branch after merging and deploying fix from #53. PR should be ready for merge now

**Pull request merged**
