### PR TITLE
Close #41: title party

### LINKED ISSUE #41: title party
go through all the titles of the headers and sections in documentation and make sure there arent any in error or missing

### PR DESCRIPTION
**Pull request by cyunis**
title party starts now

### CODE REVIEW

**Comment by cyunis** [comment]
-bolding under references is different than under other headers
-tutorials page could have some links to tutorials for hugo (if they exist on other websites i know docsy doesnt have a specific one themselves), maybe docker and how to use github?
-make a separate how to page for editing the public website called "Public Website Guides" -> maybe needs a separate issue
-github folder titling should match updated titles (ex: internal guides instead of configuration management, external guides instead of contributing to documentation, executive summary instead of project tetra overview, etc...)
-make contact link an alias on external guides page (contributing to documentation)

**Comment by capsulecorplab** [comment]
>bolding under references is different than under other headers

should be opened in a separate issue, b/c IDK how to resolve it atm

**Comment by capsulecorplab** [comment]
>tutorials page could have some links to tutorials for hugo (if they exist on other websites i know docsy doesnt have a specific one themselves), maybe docker and how to use github?

Tutorials should be reserved for assembly, build, and testing of the Project Tetra ventilator splitter unit itself, not guides for running whatever technologies power website as that's outside the scope of what the documentation site was originally intended for. Any such tutorials or guides should be added to the [Useful Resources](https://tetrabiodistributed.github.io/project-tetra-docs/how-to-guides/contribution-guidelines/#_useful_resources) section of the _Contributing to Documentation_ page.

**Review by capsulecorplab — APPROVED** [review]
Ended up removing the _Components in Development_ page, as per @Judoguy12's approval.

**Pull request merged**
